# AI Instructions Sync Script
# Syncs common instructions from .ai/INSTRUCTIONS.md to all agent-specific instruction files
# This maintains DRY while ensuring agents that can't follow references get the full content

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "AI Instructions Sync" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$sourceFile = Join-Path $PSScriptRoot "INSTRUCTIONS.md"
$targetFiles = @(
    @{
        Path = Join-Path $PSScriptRoot "..\\.github\copilot\instructions.md"
        Header = @"
# GitHub Copilot Project Guide

> **⚠️ DO NOT EDIT THIS FILE DIRECTLY**  
> This file is auto-generated from ``../../.ai/INSTRUCTIONS.md``  
> To update instructions, edit ``.ai/INSTRUCTIONS.md`` and run ``.ai/sync-instructions.ps1``

<!-- BEGIN AUTO-GENERATED CONTENT -->
"@
        Footer = @"
<!-- END AUTO-GENERATED CONTENT -->

## GitHub Copilot-Specific Instructions

*(Add any GitHub Copilot-specific instructions here if needed)*
"@
    },
    @{
        Path = Join-Path $PSScriptRoot "..\\.cursor\instructions.md"
        Header = @"
# Cursor AI Project Guide

> **⚠️ DO NOT EDIT THIS FILE DIRECTLY**  
> This file is auto-generated from ``../../.ai/INSTRUCTIONS.md``  
> To update instructions, edit ``.ai/INSTRUCTIONS.md`` and run ``.ai/sync-instructions.ps1``

<!-- BEGIN AUTO-GENERATED CONTENT -->
"@
        Footer = @"
<!-- END AUTO-GENERATED CONTENT -->

## Cursor-Specific Instructions

*(Add any Cursor-specific instructions here if needed)*
"@
    },
    @{
        Path = Join-Path $PSScriptRoot "..\\.gemini\GEMINI.md"
        Header = @"
# Gemini Project Guide

> **⚠️ DO NOT EDIT THIS FILE DIRECTLY**  
> This file is auto-generated from ``../../.ai/INSTRUCTIONS.md``  
> To update instructions, edit ``.ai/INSTRUCTIONS.md`` and run ``.ai/sync-instructions.ps1``

<!-- BEGIN AUTO-GENERATED CONTENT -->
"@
        Footer = @"
<!-- END AUTO-GENERATED CONTENT -->

## Gemini-Specific Instructions

*(Add any Gemini-specific instructions here if needed)*
"@
    }
)

# Check if source file exists
if (-not (Test-Path $sourceFile)) {
    Write-Host "ERROR: Source file not found: $sourceFile" -ForegroundColor Red
    exit 1
}

# Read source content
Write-Host "[1/2] Reading source instructions from: .ai/INSTRUCTIONS.md" -ForegroundColor Yellow
$sourceContent = Get-Content $sourceFile -Raw -Encoding UTF8

# Update each target file
Write-Host "[2/2] Syncing to agent-specific instruction files..." -ForegroundColor Yellow
$syncCount = 0

foreach ($target in $targetFiles) {
    $targetPath = $target.Path
    $relPath = (Resolve-Path $targetPath -Relative) -replace '\\', '/'
    
    # Check if target directory exists
    $targetDir = Split-Path $targetPath -Parent
    if (-not (Test-Path $targetDir)) {
        Write-Host "  [SKIP] Directory not found: $targetDir" -ForegroundColor Yellow
        continue
    }
    
    # Preserve existing agent-specific content if file exists
    $agentSpecificContent = ""
    if (Test-Path $targetPath) {
        $existingContent = Get-Content $targetPath -Raw -Encoding UTF8
        
        # Extract content after END AUTO-GENERATED CONTENT marker
        if ($existingContent -match "<!-- END AUTO-GENERATED CONTENT -->(.*)$") {
            $agentSpecificContent = $matches[1]
        }
    }
    
    # Use preserved content or default footer
    $footer = if ($agentSpecificContent.Trim()) { 
        "<!-- END AUTO-GENERATED CONTENT -->" + $agentSpecificContent 
    } else { 
        $target.Footer 
    }
    
    # Build new content
    $newContent = $target.Header + $sourceContent + "`n" + $footer
    
    # Write to file
    Set-Content -Path $targetPath -Value $newContent -Encoding UTF8 -NoNewline
    Write-Host "  [OK] Synced to: $relPath" -ForegroundColor Green
    $syncCount++
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Sync Complete!" -ForegroundColor Green
Write-Host "Synced $syncCount file(s)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
